### ISSUE TITLE
Script fails on symlink to directories

### ISSUE THREAD

**Issue by ahmadqmalzoubi** [ahmadqmalzoubi/file-duplicate-finder#3]
The script will treat symlinks to directories as files when running the `get_files_recursively` function. Then the script will fail when it tries to calculate the blake2b hash for this symlink.

The `get_files_recursively` code should check if the file is a symlink to a directory, if yes: it should be ignored.

Suggested code change to `get_files_recursively` function:
```
def get_files_recursively(baseDir):
    for dentry in os.scandir(baseDir):
        if dentry.is_dir(follow_symlinks=False):
            yield from get_files_recursively(dentry.path)
        else:
            if dentry.is_symlink():
                continue
            else:
                yield dentry
```

**Comment by ahmadqmalzoubi** [comment]
The script fails on directory symlinks:
```
ahmad@server1:~/workspace/file-duplicate-finder$ sudo ./file-duplicate-finder.py --minsize 0 /usr/
Traceback (most recent call last):
  File "/home/ahmad/workspace/file-duplicate-finder/./file-duplicate-finder.py", line 55, in <module>
    if blake2bsum_first4k(file.path) in files_dict[file_size]:
  File "/home/ahmad/workspace/file-duplicate-finder/./file-duplicate-finder.py", line 19, in blake2bsum_first4k
    with open(filename, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/usr/lib/modules/5.15.0-117-generic/build'
ahmad@server1:~/workspace/file-duplicate-finder$ 
ahmad@server1:~/workspace/file-duplicate-finder$ ls -ld /usr/lib/modules/5.15.0-117-generic/build
lrwxrwxrwx 1 root root 41 Jul  5 15:04 /usr/lib/modules/5.15.0-117-generic/build -> /usr/src/linux-headers-5.15.0-117-generic
ahmad@server1:~/workspace/file-duplicate-finder$
```

**Comment by ahmadqmalzoubi** [comment]
The script succeeded after code change
```
def get_files_recursively(baseDir):
    for dentry in os.scandir(baseDir):
        if dentry.is_dir(follow_symlinks=False):
            yield from get_files_recursively(dentry.path)
        else:
            if dentry.is_symlink():
                continue
            else:
                yield dentry
```

**Comment by ahmadqmalzoubi** [comment]
Resolved in commit https://github.com/ahmadqmalzoubi/file-duplicate-finder/commit/bf304a4a0b2cc456d48f5b763c8b22a7ba54837a
